//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ErpQualidadeModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class erp_qualidadeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new erp_qualidadeEntities object using the connection string found in the 'erp_qualidadeEntities' section of the application configuration file.
        /// </summary>
        public erp_qualidadeEntities() : base("name=erp_qualidadeEntities", "erp_qualidadeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new erp_qualidadeEntities object.
        /// </summary>
        public erp_qualidadeEntities(string connectionString) : base(connectionString, "erp_qualidadeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new erp_qualidadeEntities object.
        /// </summary>
        public erp_qualidadeEntities(EntityConnection connection) : base(connection, "erp_qualidadeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SatisfacaoClienteSet> SatisfacaoClienteSets
        {
            get
            {
                if ((_SatisfacaoClienteSets == null))
                {
                    _SatisfacaoClienteSets = base.CreateObjectSet<SatisfacaoClienteSet>("SatisfacaoClienteSets");
                }
                return _SatisfacaoClienteSets;
            }
        }
        private ObjectSet<SatisfacaoClienteSet> _SatisfacaoClienteSets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SatisfacaoFuncionarioSet> SatisfacaoFuncionarioSets
        {
            get
            {
                if ((_SatisfacaoFuncionarioSets == null))
                {
                    _SatisfacaoFuncionarioSets = base.CreateObjectSet<SatisfacaoFuncionarioSet>("SatisfacaoFuncionarioSets");
                }
                return _SatisfacaoFuncionarioSets;
            }
        }
        private ObjectSet<SatisfacaoFuncionarioSet> _SatisfacaoFuncionarioSets;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SatisfacaoClienteSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSatisfacaoClienteSets(SatisfacaoClienteSet satisfacaoClienteSet)
        {
            base.AddObject("SatisfacaoClienteSets", satisfacaoClienteSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SatisfacaoFuncionarioSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSatisfacaoFuncionarioSets(SatisfacaoFuncionarioSet satisfacaoFuncionarioSet)
        {
            base.AddObject("SatisfacaoFuncionarioSets", satisfacaoFuncionarioSet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="erp_qualidadeModel", Name="SatisfacaoClienteSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SatisfacaoClienteSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SatisfacaoClienteSet object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="data_avaliacao">Initial value of the data_avaliacao property.</param>
        /// <param name="tempo_espera">Initial value of the tempo_espera property.</param>
        /// <param name="qualidade_atendimento">Initial value of the qualidade_atendimento property.</param>
        /// <param name="outra_opiniao">Initial value of the outra_opiniao property.</param>
        /// <param name="nota_final">Initial value of the nota_final property.</param>
        /// <param name="comentarios">Initial value of the comentarios property.</param>
        public static SatisfacaoClienteSet CreateSatisfacaoClienteSet(global::System.Int32 id, global::System.String nome, global::System.DateTime data_avaliacao, global::System.Decimal tempo_espera, global::System.Decimal qualidade_atendimento, global::System.Boolean outra_opiniao, global::System.Decimal nota_final, global::System.String comentarios)
        {
            SatisfacaoClienteSet satisfacaoClienteSet = new SatisfacaoClienteSet();
            satisfacaoClienteSet.id = id;
            satisfacaoClienteSet.nome = nome;
            satisfacaoClienteSet.data_avaliacao = data_avaliacao;
            satisfacaoClienteSet.tempo_espera = tempo_espera;
            satisfacaoClienteSet.qualidade_atendimento = qualidade_atendimento;
            satisfacaoClienteSet.outra_opiniao = outra_opiniao;
            satisfacaoClienteSet.nota_final = nota_final;
            satisfacaoClienteSet.comentarios = comentarios;
            return satisfacaoClienteSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_avaliacao
        {
            get
            {
                return _data_avaliacao;
            }
            set
            {
                Ondata_avaliacaoChanging(value);
                ReportPropertyChanging("data_avaliacao");
                _data_avaliacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_avaliacao");
                Ondata_avaliacaoChanged();
            }
        }
        private global::System.DateTime _data_avaliacao;
        partial void Ondata_avaliacaoChanging(global::System.DateTime value);
        partial void Ondata_avaliacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal tempo_espera
        {
            get
            {
                return _tempo_espera;
            }
            set
            {
                Ontempo_esperaChanging(value);
                ReportPropertyChanging("tempo_espera");
                _tempo_espera = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tempo_espera");
                Ontempo_esperaChanged();
            }
        }
        private global::System.Decimal _tempo_espera;
        partial void Ontempo_esperaChanging(global::System.Decimal value);
        partial void Ontempo_esperaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal qualidade_atendimento
        {
            get
            {
                return _qualidade_atendimento;
            }
            set
            {
                Onqualidade_atendimentoChanging(value);
                ReportPropertyChanging("qualidade_atendimento");
                _qualidade_atendimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qualidade_atendimento");
                Onqualidade_atendimentoChanged();
            }
        }
        private global::System.Decimal _qualidade_atendimento;
        partial void Onqualidade_atendimentoChanging(global::System.Decimal value);
        partial void Onqualidade_atendimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean outra_opiniao
        {
            get
            {
                return _outra_opiniao;
            }
            set
            {
                Onoutra_opiniaoChanging(value);
                ReportPropertyChanging("outra_opiniao");
                _outra_opiniao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("outra_opiniao");
                Onoutra_opiniaoChanged();
            }
        }
        private global::System.Boolean _outra_opiniao;
        partial void Onoutra_opiniaoChanging(global::System.Boolean value);
        partial void Onoutra_opiniaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal nota_final
        {
            get
            {
                return _nota_final;
            }
            set
            {
                Onnota_finalChanging(value);
                ReportPropertyChanging("nota_final");
                _nota_final = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nota_final");
                Onnota_finalChanged();
            }
        }
        private global::System.Decimal _nota_final;
        partial void Onnota_finalChanging(global::System.Decimal value);
        partial void Onnota_finalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comentarios
        {
            get
            {
                return _comentarios;
            }
            set
            {
                OncomentariosChanging(value);
                ReportPropertyChanging("comentarios");
                _comentarios = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comentarios");
                OncomentariosChanged();
            }
        }
        private global::System.String _comentarios;
        partial void OncomentariosChanging(global::System.String value);
        partial void OncomentariosChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="erp_qualidadeModel", Name="SatisfacaoFuncionarioSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SatisfacaoFuncionarioSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SatisfacaoFuncionarioSet object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome_funcionario">Initial value of the nome_funcionario property.</param>
        /// <param name="codigo_funcionario">Initial value of the codigo_funcionario property.</param>
        /// <param name="data_avaliacao">Initial value of the data_avaliacao property.</param>
        /// <param name="nota_ambiente_trabalho">Initial value of the nota_ambiente_trabalho property.</param>
        /// <param name="nota_colegas_trabalho">Initial value of the nota_colegas_trabalho property.</param>
        /// <param name="nota_satisfacao_pessoal">Initial value of the nota_satisfacao_pessoal property.</param>
        /// <param name="nota_final">Initial value of the nota_final property.</param>
        /// <param name="comentarios">Initial value of the comentarios property.</param>
        public static SatisfacaoFuncionarioSet CreateSatisfacaoFuncionarioSet(global::System.Int32 id, global::System.String nome_funcionario, global::System.String codigo_funcionario, global::System.DateTime data_avaliacao, global::System.Decimal nota_ambiente_trabalho, global::System.Decimal nota_colegas_trabalho, global::System.Decimal nota_satisfacao_pessoal, global::System.Decimal nota_final, global::System.String comentarios)
        {
            SatisfacaoFuncionarioSet satisfacaoFuncionarioSet = new SatisfacaoFuncionarioSet();
            satisfacaoFuncionarioSet.id = id;
            satisfacaoFuncionarioSet.nome_funcionario = nome_funcionario;
            satisfacaoFuncionarioSet.codigo_funcionario = codigo_funcionario;
            satisfacaoFuncionarioSet.data_avaliacao = data_avaliacao;
            satisfacaoFuncionarioSet.nota_ambiente_trabalho = nota_ambiente_trabalho;
            satisfacaoFuncionarioSet.nota_colegas_trabalho = nota_colegas_trabalho;
            satisfacaoFuncionarioSet.nota_satisfacao_pessoal = nota_satisfacao_pessoal;
            satisfacaoFuncionarioSet.nota_final = nota_final;
            satisfacaoFuncionarioSet.comentarios = comentarios;
            return satisfacaoFuncionarioSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome_funcionario
        {
            get
            {
                return _nome_funcionario;
            }
            set
            {
                Onnome_funcionarioChanging(value);
                ReportPropertyChanging("nome_funcionario");
                _nome_funcionario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nome_funcionario");
                Onnome_funcionarioChanged();
            }
        }
        private global::System.String _nome_funcionario;
        partial void Onnome_funcionarioChanging(global::System.String value);
        partial void Onnome_funcionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo_funcionario
        {
            get
            {
                return _codigo_funcionario;
            }
            set
            {
                Oncodigo_funcionarioChanging(value);
                ReportPropertyChanging("codigo_funcionario");
                _codigo_funcionario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("codigo_funcionario");
                Oncodigo_funcionarioChanged();
            }
        }
        private global::System.String _codigo_funcionario;
        partial void Oncodigo_funcionarioChanging(global::System.String value);
        partial void Oncodigo_funcionarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_avaliacao
        {
            get
            {
                return _data_avaliacao;
            }
            set
            {
                Ondata_avaliacaoChanging(value);
                ReportPropertyChanging("data_avaliacao");
                _data_avaliacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_avaliacao");
                Ondata_avaliacaoChanged();
            }
        }
        private global::System.DateTime _data_avaliacao;
        partial void Ondata_avaliacaoChanging(global::System.DateTime value);
        partial void Ondata_avaliacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal nota_ambiente_trabalho
        {
            get
            {
                return _nota_ambiente_trabalho;
            }
            set
            {
                Onnota_ambiente_trabalhoChanging(value);
                ReportPropertyChanging("nota_ambiente_trabalho");
                _nota_ambiente_trabalho = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nota_ambiente_trabalho");
                Onnota_ambiente_trabalhoChanged();
            }
        }
        private global::System.Decimal _nota_ambiente_trabalho;
        partial void Onnota_ambiente_trabalhoChanging(global::System.Decimal value);
        partial void Onnota_ambiente_trabalhoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal nota_colegas_trabalho
        {
            get
            {
                return _nota_colegas_trabalho;
            }
            set
            {
                Onnota_colegas_trabalhoChanging(value);
                ReportPropertyChanging("nota_colegas_trabalho");
                _nota_colegas_trabalho = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nota_colegas_trabalho");
                Onnota_colegas_trabalhoChanged();
            }
        }
        private global::System.Decimal _nota_colegas_trabalho;
        partial void Onnota_colegas_trabalhoChanging(global::System.Decimal value);
        partial void Onnota_colegas_trabalhoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal nota_satisfacao_pessoal
        {
            get
            {
                return _nota_satisfacao_pessoal;
            }
            set
            {
                Onnota_satisfacao_pessoalChanging(value);
                ReportPropertyChanging("nota_satisfacao_pessoal");
                _nota_satisfacao_pessoal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nota_satisfacao_pessoal");
                Onnota_satisfacao_pessoalChanged();
            }
        }
        private global::System.Decimal _nota_satisfacao_pessoal;
        partial void Onnota_satisfacao_pessoalChanging(global::System.Decimal value);
        partial void Onnota_satisfacao_pessoalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal nota_final
        {
            get
            {
                return _nota_final;
            }
            set
            {
                Onnota_finalChanging(value);
                ReportPropertyChanging("nota_final");
                _nota_final = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nota_final");
                Onnota_finalChanged();
            }
        }
        private global::System.Decimal _nota_final;
        partial void Onnota_finalChanging(global::System.Decimal value);
        partial void Onnota_finalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comentarios
        {
            get
            {
                return _comentarios;
            }
            set
            {
                OncomentariosChanging(value);
                ReportPropertyChanging("comentarios");
                _comentarios = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comentarios");
                OncomentariosChanged();
            }
        }
        private global::System.String _comentarios;
        partial void OncomentariosChanging(global::System.String value);
        partial void OncomentariosChanged();

        #endregion
    
    }

    #endregion
    
}
